apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appjava
  name: appjava
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appjava
  strategy: {}
  template:
    metadata:
      labels:
        app: appjava
    spec:
      volumes:
      - name: vol
        emptyDir: {}
      serviceAccountName: default
      containers:
      - image: replace
        name: appjava-container
        volumeMounts:
        - mountPath: /tmp
          name: vol
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: appjava
  name: appjava-svc
spec:
  ports:
  - port: 5555
    protocol: TCP
    targetPort: 8080
  selector:
    app: appjava
  type: NodePort
